config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'users#show_login_form'
  post '/login', to: 'users#do_login'

  post '/logout', to: 'users#do_logout'

  get '/register', to: 'users#show_register_form'
  post '/register', to: 'users#do_create_user'

  get '/friends', to: 'users#show_friend_list'
  post '/friends/add', to: 'users#befriend', as: :befriend
  post '/friends/remove', to: 'users#unfriend', as: :unfriend
  post '/friends/block', to: 'users#block_friend', as: :block_friend
  post '/friends/unblock', to: 'users#unblock_friend', as: :unblock_friend

  get '/messages/inbox', to: 'messages#show_inbox', as: :inbox
  get '/messages/outbox', to: 'messages#show_outbox', as: :outbox
  get '/messages/new', to: 'messages#show_new_message_form', as: :send_new_message
  post '/messages/new', to: 'messages#do_send_message'

  get '/messages/:id', to: 'messages#view_message', as: :view_message
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  def self.befriend(my_id, your_id)
    Friendship.create(my_id: my_id, friend_id: your_id)
    Friendship.create(my_id: your_id, friend_id: my_id)
  end

  def self.unfriend(my_id, your_id)
    Friendship.where(my_id: my_id, friend_id: your_id).delete_all
    Friendship.where(my_id: your_id, friend_id: my_id).delete_all
  end

  def self.block_friend(my_id, friend_id)
    friendship = Friendship.where(my_id: my_id, friend_id: friend_id).take
    friendship.update(is_blocked: true)
  end

  def self.unblock_friend(my_id, friend_id)
    friendship = Friendship.where(my_id: my_id, friend_id: friend_id).take
    friendship.update(is_blocked: false)
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, class_name: 'User'

  attr_accessor :seen, :seen_at

  def deliver_to(recipients)
    message_id = self.id
    recipient_ids = recipients.split(',')
    recipient_ids.each do |recipient_id|
      MessageDelivery.create(message_id: message_id, recipient_id: recipient_id)
    end
  end

  def sender?(user)
    sender_id == user.id
  end

  def recipient?(user)
    MessageDelivery.exists?(message_id: self.id, recipient_id: user.id)
  end

  def read_by?(user)
    MessageDelivery.where(message_id: self.id, recipient_id: user.id).take.seen
  end

  def read_now(user)
    MessageDelivery
        .where(message_id: self.id, recipient_id: user.id)
        .update_all(seen: true, seen_at: DateTime.now)
  end
end

app/models/message_delivery.rb
class MessageDelivery < ActiveRecord::Base
  belongs_to :message
  belongs_to :recipient, class_name: 'User'

  def self.received_messages(recipient)
    blocked_ids = Friendship.where(my_id: recipient.id, is_blocked: true).pluck(:friend_id).map(&:to_i)
    query = MessageDelivery
                .includes(:message)
                .where('message_deliveries.recipient_id': recipient.id)
                .order('message_deliveries.created_at DESC')
    if blocked_ids.present?
      query = query.where.not('messages.sender_id': blocked_ids)
    end
    query
  end

  def self.sent_messages(sender)
    MessageDelivery
        .includes(:recipient)
        .joins(:message)
        .where('messages.sender_id' => sender.id)
        .order('message_deliveries.created_at DESC')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, uniqueness: true, presence: true
  validates :password_confirmation, presence: true

  def friends
    User
        .joins('join friendships on friendships.friend_id = users.id')
        .where('friendships.my_id = ?', self.id)
        .select('users.*, friendships.is_blocked')
  end

  def strangers
    User.where.not(id: (friends.ids << self.id))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :require_login

  helper_method :current_user

  def require_login
    redirect_to login_path unless authenticated?
  end

  def skip_login
    redirect_to inbox_path if authenticated?
  end

  def authenticated?
    !!current_user
  end

  def current_user
    User.find_by_id(session[:user_id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def show_inbox
    @messages = MessageDelivery.received_messages(current_user)
    render('inbox')
  end

  def show_outbox
    @messages = MessageDelivery.sent_messages(current_user)
    render('outbox')
  end

  def show_new_message_form
    @friends_json = current_user.friends.to_json(:only => [:id, :name])
    render('new_message_form')
  end

  def do_send_message
    Message
        .create(sender_id: current_user.id, body: params[:content])
        .deliver_to(params[:recipients])
    redirect_to(outbox_path)
  end

  def view_message
    @message = Message.find_by_id(params[:id])
    if @message.sender?(current_user)
      @error = 'You cannot view this message because you sent it.'
    elsif @message.recipient?(current_user)
      if @message.read_by?(current_user)
        @error = 'You already read this message.'
      else
        @message.read_now(current_user)
      end
    else
      @error = 'You do not have permission to view this message.'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :require_login, only: [:show_login_form, :do_login, :show_register_form, :do_create_user]

  before_action :skip_login, only: [:show_login_form, :show_register_form]

  def show_login_form
    render 'users/login'
  end

  def do_login
    @user = User.find_by_email(params[:email]).try(:authenticate, params[:password])
    if !!@user
      store_id_and_redirect_to_home(@user)
    else
      flash[:error] = 'Invalid email or password'
      redirect_to login_path
    end
  end

  def show_register_form
    @user = User.new
    render 'users/register'
  end

  def do_create_user
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      store_id_and_redirect_to_home(@user)
    else
      render 'users/register'
    end
  end

  def do_logout
    reset_session
    redirect_to login_path
  end

  def show_friend_list
    @strangers = current_user.strangers
    @friends = current_user.friends
    render 'friend_list'
  end

  def befriend
    Friendship.befriend(current_user.id, params[:friend_id])
    redirect_to(friends_path)
  end

  def unfriend
    Friendship.unfriend(current_user.id, params[:friend_id])
    redirect_to(friends_path)
  end

  def block_friend
    Friendship.block_friend(current_user.id, params[:friend_id])
    redirect_to(friends_path)
  end

  def unblock_friend
    Friendship.unblock_friend(current_user.id, params[:friend_id])
    redirect_to(friends_path)
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def store_id_and_redirect_to_home(user)
    session[:user_id] = user.id
    redirect_to inbox_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def friendly_validation_message(validation_result, field)
    validation_result.errors.full_messages_for(field).join('. ')
  end

  def validation_error_class(validation_result, field)
    validation_result.errors[field].empty? ? '' : 'has-error'
  end

  def bootstrap_class_for(flash_type)
    {success: 'alert-success', error: 'alert-danger', alert: 'alert-warning', notice: 'alert-info'}[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
        concat message
      end)
    end
    nil
  end

  def seen_status(message)
    if message.seen
      message.seen_at.strftime('Read at %I:%M %p %m/%d/%Y')
    else
      'Unread'
    end
  end

  def row_style(message)
    if message.seen
      ''
    else
      'info'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coderchat</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/messages/inbox.html.erb
<%= render 'shared/header' %>

<h3>Inbox</h3>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-primary">
      <div class="panel-heading"><h4>Received messages</h4></div>
      <div class="panel-body">
        <table class="table table-hover vertical-centered">
          <thead>
          <tr>
            <th>From</th>
            <th>Status</th>
            <th>Action</th>
          </tr>
          </thead>
          <tbody>
          <% @messages.each do |m| %>
              <tr class="<%= row_style(m) %>">
                <td><%= m.message.sender.name %></td>
                <td><%= seen_status(m) %></td>
                <td><a href="<%= view_message_path(m.message_id) %>">View</a></td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/messages/index.html.erb
<%= render 'shared/header' %>

app/views/messages/new_message_form.html.erb
<%= render 'shared/header' %>

<form action="<%= send_new_message_path %>" method="post">
  <%= token_tag %>

  <div class="form-group">
    <label for="recipients">Recipients</label>
    <input type="text" class="form-control"
           autocomplete="off" data-role="user-picker"
           data-users="<%= @friends_json %>"
           id="recipients" name="recipients"/>
  </div>

  <div class="form-group">
    <label for="content">Content</label>
    <textarea class="form-control" rows="3" id="content" name="content" placeholder="Hi there"></textarea>
  </div>

  <button type="submit" class="btn btn-default">Send</button>
</form>

app/views/messages/outbox.html.erb
<%= render 'shared/header' %>

<h3>Outbox</h3>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-primary">
      <div class="panel-heading"><h4>Sent messages</h4></div>
      <div class="panel-body">
        <table class="table table-hover vertical-centered">
          <thead>
          <tr>
            <th>To</th>
            <th>Status</th>
            <th>Action</th>
          </tr>
          </thead>
          <tbody>
          <% @messages.each do |m| %>
              <tr class="<%= row_style(m) %>">
                <td><%= m.recipient.name %></td>
                <td><%= seen_status(m) %></td>
                <td><a href="<%= view_message_path(m.message_id) %>">View</a></td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/messages/view_message.html.erb
<%= render 'shared/header' %>

<% if @error %>
    <div class="alert alert-danger" role="alert">
      <span class="sr-only">Error:</span>
      <%= @error %>
    </div>
<% else %>
    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-primary">
          <div class="panel-heading"><h4>From: <%= @message.sender.name %></h4></div>
          <div class="panel-body">
            <%= @message.body %>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <p class="navbar-text navbar-link">Welcome to Coderchat, <%= current_user.name %></p>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            Messages
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><a href="<%= inbox_path %>">Inbox</a></li>
            <li><a href="<%= outbox_path %>">Outbox</a></li>
            <li><a href="<%= send_new_message_path %>">Send new message</a></li>
          </ul>
        </li>
        <li><a href="<%= friends_path %>">Friends</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <form action="<%= logout_path %>" method="post">
            <%= token_tag %>
            <button class="btn btn-link navbar-btn" type="submit">Logout</button>
          </form>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/users/friend_list.html.erb
<%= render 'shared/header' %>

<div class="row">
  <div class="col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading"><h4>Friends</h4></div>
      <div class="panel-body">
        <table class="table table-striped table-hover vertical-centered">
          <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th colspan="2">Action</th>
          </tr>
          </thead>
          <tbody>
          <% @friends.each do |user| %>
              <tr>
                <td><%= user.name %></td>
                <td><%= user.email %></td>
                <td>
                  <form method="post" action="<%= unfriend_path %>">
                    <%= token_tag %>
                    <input type="hidden" name="friend_id" value="<%= user.id %>"/>
                    <button type="submit" class="btn btn-sm btn-danger">Unfriend</button>
                  </form>
                </td>
                <td>
                  <% if user.is_blocked %>
                      <form method="post" action="<%= unblock_friend_path %>">
                        <%= token_tag %>
                        <input type="hidden" name="friend_id" value="<%= user.id %>"/>
                        <button type="submit" class="btn btn-sm btn-primary">Unblock</button>
                      </form>
                  <% else %>
                      <form method="post" action="<%= block_friend_path %>">
                        <%= token_tag %>
                        <input type="hidden" name="friend_id" value="<%= user.id %>"/>
                        <button type="submit" class="btn btn-sm btn-warning">Block</button>
                      </form>
                  <% end %>
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading"><h4>Users</h4></div>
      <div class="panel-body">
        <table class="table table-striped table-hover vertical-centered">
          <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Action</th>
          </tr>
          </thead>
          <tbody>
          <% @strangers.each do |user| %>
              <tr>
                <td><%= user.name %></td>
                <td><%= user.email %></td>
                <td>
                  <form method="post" action="<%= befriend_path %>">
                    <%= token_tag %>
                    <input type="hidden" name="friend_id" value="<%= user.id %>"/>
                    <button type="submit" class="btn btn-sm btn-primary">Befriend</button>
                  </form>
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/users/login.html.erb
<div class="col-md-8">
  <h2>Log in</h2>

  <%= flash_messages %>

  <form method="post" action="<%= login_path %>">
    <%= token_tag %>
    <div class="form-group">
      <label for="email">Email address</label>
      <input type="email" class="form-control" id="email" name="email" placeholder="john@example.com"/>
    </div>
    <div class="form-group">
      <label for="password">Password</label>
      <input type="password" class="form-control" id="password" name="password"/>
    </div>
    <button type="submit" class="btn btn-primary">Log in</button>
  </form>
</div>

app/views/users/register.html.erb
<div class="col-md-8">
  <h2>Register a new account</h2>
  <form method="post" action="<%= register_path %>">
    <%= token_tag %>
    <div class="form-group">
      <label for="name">Name</label>
      <input type="text" class="form-control" id="name" name="user[name]" placeholder="John Doe"/>
    </div>
    <div class="form-group <%= validation_error_class(@user, :email) %>">
      <label for="email">Email address</label>
      <input type="email" class="form-control" id="email" name="user[email]" placeholder="john@example.com"/>
      <% if @user.errors[:email].any? %>
          <span class="help-block"><%= friendly_validation_message(@user, :email) %></span>
      <% end %>
    </div>
    <div class="form-group <%= validation_error_class(@user, :password) %>">
      <label for="password">Password</label>
      <input type="password" class="form-control" id="password" name="user[password]"/>
      <% if @user.errors[:password].any? %>
          <span class="help-block"><%= friendly_validation_message(@user, :password) %></span>
      <% end %>
    </div>
    <div class="form-group <%= validation_error_class(@user, :password_confirmation) %>">
      <label for="password-confirmation">Confirm password</label>
      <input type="password" class="form-control" id="password-confirmation" name="user[password_confirmation]"/>
      <% if @user.errors[:password_confirmation].any? %>
          <span class="help-block"><%= friendly_validation_message(@user, :password_confirmation) %></span>
      <% end %>
    </div>
    <button type="submit" class="btn btn-primary">Register</button>
  </form>
</div>